apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mds-pir
  namespace: default
spec:
  selector:
    matchLabels:
      name: mds-pir
  template:
    metadata:
      labels:
        name: mds-pir
    spec:
      containers:
      - name: pir2motion
        image: kszicsillag.azurecr.io/pir2motion
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: sysgpio
          mountPath: /sys
        - name: vcsm
          mountPath: /dev/vcsm
        - name: vchiq
          mountPath: /dev/vchiq
        - name: rclone
          mountPath: /etc/rclone
        - name: cam
          mountPath: /cam
      imagePullSecrets:
        - name: acr-kszicsillag
      terminationGracePeriodSeconds: 30
      volumes:
        - name: sysgpio
          hostPath:
            path: /sys
        - name: vcsm
          hostPath:
            path: /dev/vcsm
        - name: vchiq
          hostPath:
            path: /dev/vchiq
        - name: rclone
          hostPath:
            path: /etc/rclone
        - name: cam
          hostPath:
            path: /cam
